config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # 3.deviseが最初に来てない
  devise_for :users
  root :to =>"homes#top"
  get "home/about"=>"homes#about"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create,:destroy]
    resources :book_comments, only: [:create,:destroy]
  end

  resources :users, only: [:index,:show,:edit,:update]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/search', to: 'searches#search'
# 1.endがない
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}


# 検索方法分岐
  # def self.looks(search, word)
  #   if search == "perfect_match"
  #     @book = Book.where("title LIKE?","#{word}")
  #   elsif search == "forward_match"
  #     @book = Book.where("title LIKE?","#{word}%")
  #   elsif search == "backward_match"
  #     @book = Book.where("title LIKE?","%#{word}")
  #   elsif search == "partial_match"
  #     @book = Book.where("title LIKE?","%#{word}%")
  #   else
  #     @book = Book.all
  #   end
  # end

end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/group.rb
class Group < ApplicationRecord
  validates :name, presence: true
  validates :introduction, presence: true
  attachment :image, destroy: false

  has_many :group_users
  has_many :users, through: :group_users


end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/message.rb
class Message < ApplicationRecord
  validates :message, presence: true, length: { minimum: 1, maximum: 140 }
  belongs_to :user
  belongs_to :room
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  # belongs_to :books
  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  # validates :introduction抜け
  validates :introduction, length: { maximum: 50 }# 「50文字以内」


   # 画像の保存設定
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  # 検索方法分岐
  # def self.looks(search, word)
  #   if search == "perfect_match"
  #     @user = User.where("name LIKE?", "#{word}")
  #   elsif search == "forward_match"
  #     @user = User.where("name LIKE?","#{word}%")
  #   elsif search == "backward_match"
  #     @user = User.where("name LIKE?","%#{word}")
  #   elsif search == "partial_match"
  #     @user = User.where("name LIKE?","%#{word}%")
  #   else
  #     @user = User.all
  #   end
  # end

end

app/models/view_count.rb
class ViewCount < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def show
    @newbook = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
  end

  def index
    @user = current_user
    @book = Book.new
    # @books = Book.all
    # if params[:option] == "A" || params[:option] == nil
    #   @books = Book.all.order(created_at: :desc)
    # elsif params[:option] == "B"
    #   @books = Book.all.order(rate: :desc)
    # end

    if params[:sort_new]
      @books = Book.all.order(created_at: :desc)
    elsif params[:sort_review]
      @books = Book.all.order(rate: :desc)
    else
      @books = Book.all
    end

  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id), notice: "You have created book successfully."
    else
      @user = current_user
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render "edit"
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    @book.user_id = current_user.id
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    if @book.destroy
      flash[:notice]="Book was successfully destroyed."
      redirect_to books_path
    end
  end

  def search_book
     @book=Book.new
     @books = Book.search(params[:keyword])
  end

  private

  def book_params
    params.require(:book).permit(:title,:body,:rate, :category)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

   before_action :authenticate_user!

  def create
    @room = Room.create
    # 現在ログインしているユーザーのidと@roomのidを保存する
    @entry1 = Entry.create(room_id: @room.id, user_id: current_user.id)
    # ユーザーに押されたユーザーの情報保存、users/_infoのviewの@entryを保存するためpermitで許可
    @entry2 = Entry.create(params.require(:entry).permit(:user_id, :room_id).merge(room_id: @room.id))
    # チャットを開く
    redirect_to "/rooms/#{@room.id}"
  end

  def show
    @room = Room.find(params[:id])
    # Entryに既存のroom（現在ログインしているユーザーとroomの組み合わせがあるか）を確認
    if Entry.where(user_id: current_user.id,room_id: @room.id).present?
    # 条件がtrueだったら、Messageテーブルにそのチャットルームのidと紐づいたメッセージを表示させるため、@messagesにアソシエーションを利用した@room.messagesという記述を代入します。
      @messages = @room.messages
      @message = Message.new
      @entries = @room.entries
    else
      redirect_back(fallback_location: root_path)
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:update]

  def show
    @user = User.find(params[:id])
    @book = Book.new
    # @books = @user.books.page(params[:page]).reverse_order
    @books = Book.where(user_id: @user.id)
    @today_book = @books.created_today
    @yesterday_book = @books.created_yesterday
    @this_week_book = @books.created_this_week
    @last_week_book = @books.created_last_week

    @users_count = User.group_by_day(:created_at).size
        # ユーザー登録数グラフ出力gem groupdateをインストールしないと上記の記述は使用不可
    @user_today = User.where(created_at: Date.today.all_day).count
        # ユーザーの1日の登録数
  end

  def index
    @users = User.all
    @book = Book.new
  # 2.endがない
  end

  def edit
    @user = User.find(params[:id])
    # 他ユーザーのページの場合自分のページに移動
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(current_user), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  #一部抜粋
  def search
    @user = User.find(params[:user_id])
    @books = @user.books
    @book = Book.new
    if params[:created_at] == ""
      @search_book = "日付を選択してください"
    else
      create_at = params[:created_at]
      @search_book = @books.where(['created_at LIKE ? ', "#{create_at}%"]).count
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<%= form_with model:book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.label :category %>
    <%= f.text_field:category %>
  </div>

  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>


  <!--星評価機能-->
  <div class="form-group" id="star">
    <%= f.label :rate, "星評価：" %>
    <%= f.hidden_field :rate, id: :review_star %>
  </div>
  <script>
    $('#star').raty({
      size     : 36,
      starOff:  '<%= asset_path('star-off.png') %>',
      starOn : '<%= asset_path('star-on.png') %>',
      starHalf: '<%= asset_path('star-half.png') %>',
      scoreName: 'book[rate]',
      half: true,
    });
  </script>




<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <%= render 'layouts/errors', obj: @book %>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to(book.user) do %>
          <%= image_tag book.user.get_profile_image(50,50) %>
          <% end %>
        </td>
        <td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>

        <!--ajaxで変更したい箇所にidを付ける-->
        <!--<div id="favorite_buttons">-->
        <td id="favorite_buttons_<%= book.id %>">
          <%= render "favorites/favorite", book: book %>
        </td>

        <!--ajaxで変更したい箇所にidを付ける-->
        <!--コメント件数表示-->
        <!--<td><span>< %= link_to "#{book.book_comments.count} コメント", book_path(book.id), class:"text-dark" %></span></td>-->


<td><span><%= link_to "#{book.book_comments.count} コメント", book_path(book.id), class:"text-dark" %></span></td>

        <!--<td id="comment_buttons1_<　%= book.id %>">-->
        <!--  < %= render "book_comments/comment1", book: book %>-->
        <!--</td>-->
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/_search.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= image_tag book.user.get_profile_image(50,50) %></td>
        <td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
        <td></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <%= render 'layouts/errors', obj: @book %>
  		<h1>Editing Book</h1>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', @book, class: "book_#{@book.id}" %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-12 text-center'>
      <%= render 'searches/form' %>
    </div>
  </div>


  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'index', books: @books%>
    </div>
  </div>
</div>

app/views/books/search_book.html.erb
<h2>カテゴリー検索結果</h2>
<table class='table table-hover table-inverse'>
  <%= render 'layouts/errors', obj: @book %>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th>Category</th>
      <th>Review</th>

    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
    <tr>
      <td>
        <%= link_to user_path(book.user.id) do %>
          <%= image_tag book.user.get_profile_image(50,50) %>
        <% end %>
      </td>
      <td><%= link_to book_path(book.id) do %><%= book.title %><% end %></td>
      <td><%= book.body %></td>
      <td><%= link_to book.category, search_book_path(keyword: book.category) %></td>
      <!--星評価表示機能-->
      <td>
      <div class="relative-book-rate">
        <span>評価：</span>
        <span id="star-rate-<%= book.id %>"></span>
        <script>
          $('#star-rate-<%= book.id %>').raty({
            size: 36,
            starOff: "<%= asset_path('star-off.png') %>",
            starOn: "<%= asset_path('star-on.png') %>",
            starHalf: "<%= asset_path('star-half.png') %>",
            half: true,
            readOnly: true,
            score: "<%= book.rate %>",
          });
        </script>
        <%= book.rate %>
      </div>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info' ,user:@user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @newbook %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
          <td><%= link_to(@book.user) do %>
          <!--size:"100x100"-->
            <%= image_tag @book.user.get_profile_image(100,100) %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, @book %></td>
          <td><%= @book.body %></td>
          <% if @book.user_id == current_user.id %>
            <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success edit_book_#{@book.id}" %></td>
            <td><%= link_to 'Destroy', @book, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_book_#{@book.id}"%></td>
          <% end %>

          <!--ajaxで変更したい箇所にidを付ける-->
          <!--<div id="favorite_buttons2">-->
          <td id="favorite_buttons_<%= @book.id %>">
            <%= render "favorites/favorite", book: @book %>
          </td>
          <td><p class="view-count">閲覧数: <%= @book.view_counts.count %></p></td>

        </tr>
      </table>

       <%= form_with model: [@book, @book_comment], data: {remote: true} do |f| %>
      <!--data: {remote: true}-->
        <%= f.text_area :comment, rows: '5', placeholder: "コメントをここに" %>
        <%= f.submit "送信する" %>
      <% end %>
      <table class='table' id="comment_buttons2_<%= @book.id %>">
        <%= render "book_comments/comment2", book: @book %>
      </table>

       <!--コメント機能-->
    </div>
  </div>
</div>

app/views/rooms/show.html.erb
<div class="left-button">
  <%= link_to "ユーザー一覧に戻る", "/users",class:"edit-link" %>
</div>
<h4 class="rooms-title">気になる同士</h4>
<% @entries.each do |e| %>
  <div class="user-name">
  <strong>
    <!--avatar-->
    <%= image_tag e.user.get_profile_image(100,100) %>
    <!--< %= image_tag e.user.avatar, class:"user-image" %>-->
      <a class="rooms-user-link" href="/users/<%= e.user.id %>">
        <%= e.user.name %>さん
      </a>
  </strong>
  </div>
<% end %>
<hr>
<div class="chats">
  <div class="chat">
    <!--messagesがあれば呼び出す-->
    <% if @messages.present? %>
      <% @messages.each do |m| %>
        <div class="chat-box">
          <div class="chat-face">
            <%= image_tag m.user.get_profile_image(100,100) %>
            <!--< %= image_tag m.user.avatar, class:"user-image" %>-->
          </div>
          <div class="chat-hukidashi"> <strong><%= m.message %></strong> <br>
            <%= m.created_at.strftime("%Y-%m-%d %H:%M")%>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="posts">
    <%= form_for @message do |f| %>
      <%= f.text_field :message, placeholder: "メッセージを入力して下さい" , size: 70, class:"form-text-field" %>
        <%= f.hidden_field :room_id, value: @room.id %>
          <%= f.submit "投稿",class: 'form-submit'%>
    <% end %>
  </div>
</div>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="4"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image(50,50) %></td>
        <td><%= user.name %></td>
        <td>フォロー数:<%= user.following_user.count %></td>
        <td>フォロワー数:<%= user.follower_user.count %></td>

        <!--フォロー登録、解除ボタン-->
        <% if current_user != user %>
          <% if current_user.following?(user) %>
            <td><%= link_to 'フォロー外す', user_relationships_path(user.id), method: :delete, class: "btn-sm btn-link" %></td>
          <% else %>
            <td><%= link_to 'フォローする', user_relationships_path(user.id), method: :POST, class:"btn-sm btn-link" %></td>
          <% end %>
        <% else %>
          <td></td>
        <% end %>

        <td><%= link_to 'Show', user, class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <!--size:'10D0x100'-->
  <tr><%= image_tag user.get_profile_image(100,100) %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>

  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>

  </tr>
  <tr>
    <th>follows</th>
    <th><%= link_to user.following_user.count, follows_user_path(user) %></th>
  </tr>
  <tr>
    <th>followers</th>
    <th><%= link_to user.follower_user.count, followers_user_path(user) %></th>
  </tr>


</table>

<!--本人の時のみプロフフィール編集ボタン表示にする-->
<% if current_user == @user %>
  <div class='row'>
    <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block edit_user_#{user.id}" do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
  </div>
<% end %>

app/views/users/_search.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Name</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% users.each do |user| %>
    <tr>
      <td><%= image_tag user.get_profile_image(50,50) %></td>
      <td><%= user.name %></td>
      <td><%= link_to 'Show', user, class: "user_#{user.id}" %></td>
    </tr>
  <% end %>
</tbody>
</table>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <!--nameがtitleになっている-->
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/followers.html.erb
  <div class="container">
    <div class="row">
      <div class='col-md-12'>

        <table class='table table-hover table-inverse'>
          <h1>Follower User</h1>
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th></th>
              <th></th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <tr>
            <% @users.each do |user| %>

                  <td><%= image_tag user.get_profile_image(30,30) %></td>
                  <td><%= user.name %></td>
                  <td>フォロー数:<%= user.following_user.count %></td>
                  <td>フォロワー数:<%= user.follower_user.count %></td>
                  <td><%= link_to "Show",user_path(user) %></td>

            <% end %>
            </tr>
          </tbody>
        </table>

      </div>
    </div>
    <%= paginate @users %>
  </div>

app/views/users/follows.html.erb
<div class="container">
    <div class="row">
      <div class='col-md-12'>

        <table class='table table-hover table-inverse'>
          <h1>Follow User</h1>
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th></th>
              <th></th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <tr>
            <% @users.each do |user| %>

                  <td><%= image_tag user.get_profile_image(30,30) %></td>
                  <td><%= user.name %></td>
                  <td>フォロー数:<%= user.following_user.count %></td>
                  <td>フォロワー数:<%= user.follower_user.count %></td>
                  <td><%= link_to "Show",user_path(user) %></td>

            <% end %>
            </tr>
          </tbody>
        </table>

      </div>
    </div>
    <%= paginate @users %>
  </div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <!--エラーメッセージ-->


  <div class="row">
    <!--<div class="col-md-3">-->
    <div class="col-md-3">
      <h2>User info</h2>
      <%= render 'info', user: current_user %>

      <h2 class="mt-3">New book</h2>
      <!--'books/form'が'form'になっている-->
      <%= render 'books/form', book: @book %>
    </div>


    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <%= render 'index',users: @users %>
    </div>

  </div>
</div>

app/views/users/search.js.erb
$("#search_result").html("<%= j(render 'search', search_book: @search_book) %>");

app/views/users/show.html.erb
<!--Chart.jsについて、、CDN方式で読み込む場合-->
<!--<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.7.1/chart.min.js" integrity="sha512-QSkVNOCYLtj73J4hbmVoOV6KVZuMluZlioC+trLpewV8qMjsWqlIQvkn1KGX2StWvPMdWGBqim1xlC8krl1EKQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>-->
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
    </div>
  </div>
</div>


<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-12'>
        <table class="table table-bordered">
           <thead>
            <tr>
             <th>６日前</th>
             <th>5日前</th>
             <th>4日前</th>
             <th>3日前</th>
             <th>２日前</th>
             <th>昨日</th>
             <th>今日</th>
            </tr>
           </thead>
           <tbody>
            <tr>
             <th><%= @books.created_6days.count %></th>
             <th><%= @books.created_5days.count %></th>
             <th><%= @books.created_4days.count %></th>
             <th><%= @books.created_3days.count %></th>
             <th><%= @books.created_2days.count %></th>
             <th><%= @yesterday_book.count %></th>
             <th><%= @today_book.count %></th>
            </tr>
           </tbody>
        </table>

        <canvas id="myChart" width="300" height="100"> </canvas>

            <script>
                var ctx = document.getElementById("myChart").getContext('2d');
                var myChart = new Chart(ctx, {
                    type: 'line',
                    data: {
                        // 横ラベル
                        labels: ['6日前', '5日前', '4日前', '3日前', '2日前', '1日前', '今日'],
                        datasets: [{
                            label: "投稿した本の数",
                            data: [<%= @books.created_6days.count %>, <%= @books.created_5days.count %>, <%= @books.created_4days.count %>, <%= @books.created_3days.count %>, <%= @books.created_2days.count %>, <%= @yesterday_book.count %>, <%= @today_book.count%>],
                            backgroundColor: 'white',
                            // borderColor: 'rgba(255, 80, 120, 1.0)',
                            borderColor: 'blue',
                            // 曲線にする
                            tension: 0.4,
                            fill: false
                        }]
                    },

        options: {
          // タイトルが読み込めない
            title: {
              display: true,
              text: '7日間の投稿数の比較'
            },
            responsive: true,
            scales: {
              y:{
                suggestedMin: 0,
                suggestedMax: 10
              },
              x:{
                stacked: true
              },
            },
        }

                });
            </script>
    </div>
    </div>
  </div>
</div>